### ISSUE TITLE
Go Client Usage

### ISSUE THREAD

**Issue by asim** [rubrikinc/kronos#1]
Hi, I like where this is going. I'm working on [go-sync](https://github.com/micro/go-sync) with a time package that needs distributed time synchronization. NTP is one package that we have but I'm looking for other services. Kronos fits the bill.

Can you please provide an example of Go client usage. I can see a snippet for starting a server, I can also see the code for the CLI but would really like a straight forward example for client usage. Maybe even a simple sdk as part of this repo so that any underlying changes are supported.

Thanks

**Comment by mvijaykarthik** [comment]
I have added an example Go client usage to the README. Let me know if it helps!

**Comment by asim** [comment]
Thanks that's useful
